spring.application.name=Routing-Service
## Pull the configs from this port
spring.config.import=configserver:http://localhost:9080

## OpenRouteService Secrets
vehicle.type = driving-hgv
osr.api.key= eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjFiYjMzMWZhNTA0YjQ0YTU5NjRiM2NkNTc2ZTg3ODIzIiwiaCI6Im11cm11cjY0In0=
