spring.application.name=Auth-Service
## Import Configurations from here.
spring.config.import=configserver:http://localhost:9080
spring.jpa.hibernate.ddl-auto=update

spring.security.oauth2.client.registration.google.client-id=GOOGLE_CLIENT_ID_PLACEHOLDER
spring.security.oauth2.client.registration.google.client-secret=GOOGLE_CLIENT_SECRET_PLACEHOLDER
spring.security.oauth2.client.registration.google.scope=openid,email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:9040/login/oauth2/code/google

oauth2.success-redirect-url=http://localhost:5173/oauth/success
