spring.application.name=Auth-Service
spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:9080}
spring.cloud.config.enabled=${SPRING_CLOUD_CONFIG_ENABLED:false}
spring.cloud.config.import-check.enabled=false

jwt.SecretKey=${JWT_SECRETKEY}

spring.security.oauth2.client.registration.google.client-id=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_SCOPE:openid,email,profile}
spring.security.oauth2.client.registration.google.redirect-uri=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI}

oauth2.success-redirect-url=${OAUTH2_SUCCESS_REDIRECT_URL:http://localhost:5173/oauth/success}
