spring.application.name=Notification-Service
spring.config.import=configserver:http://localhost:9080

resend.api-key=re_LnSkctd3_LCB2sYreEiMHgACJ4VBd8N5m
resend.from-email=SwiftShip <onboarding@resend.dev>
