spring.application.name=Notification-Service
spring.config.import=configserver:http://localhost:9080

resend.api-key=${RESEND_API_KEY:}
resend.from-email=${RESEND_FROM_EMAIL:SwiftShip <onboarding@resend.dev>}
